version: "3.8"
services:
  api:
    build: ./api
    container_name: api_container
    ports:
      - '3005:3005'
    volumes:
      - ./api:/app
      - /app/node_modules

  frontend:
    build: ./frontend
    container_name: frontend_container
    ports:
      - '3000:3000'
    stdin_open: true
    tty: true
